# Generated by Django 3.0.5 on 2020-05-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200503_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
